name: Test, build, deploy
env:
  ENTRY: 23
  GH_PAGES_DOMAIN: data.prgblockweek.com
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ env.TAG }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Prague"
      - run: "deno run --allow-run utils/tag.js >> $GITHUB_ENV"
      - run: "echo \"Tag: ${{ env.TAG }}\""
      - run: "make tag=${{ env.TAG }}"
      - run: find dist
      - uses: montudor/action-zip@v1
      - run: "zip -qq -r release.zip dist"
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: release.zip
  release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: "echo \"TAG=${{ needs.build.outputs.tag }}\" >> $GITHUB_ENV"
      - run: "echo \"Tag: ${{ env.TAG }}\""
      - uses: actions/download-artifact@v3
        with:
          name: release
      - uses: montudor/action-zip@v1
      - run: unzip -qq release.zip
      - run: "zip -qq -r ../pbw-${{ env.ENTRY }}-${{ env.TAG }}.zip ${{ env.ENTRY }}"
        working-directory: ./dist
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ env.TAG }}"
          message: "Latest release"
          github_token: '${{ secrets.GITHUB_TOKEN }}'
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.TAG }}"
          name: "${{ env.TAG }}"
          body: "This is a automated release."
          draft: false
          prerelease: false
          files: |
            pbw-${{ env.ENTRY }}-${{ env.TAG }}.zip
  pages:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: release
      - uses: montudor/action-zip@v1
      - run: unzip -qq release.zip
      - run: find dist
      - run: "touch dist/CNAME && echo \"${{ env.GH_PAGES_DOMAIN }}\" >> dist/CNAME"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist